//this is where the json data is stored and passes data between the 2 pages.
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';
 
@Injectable()
export class Data {
data: any;
  constructor(public http: Http) {
    this.data = [
	{code: 1,name: 'Basic Sciences Building',profilePic: 'assets/img/BSB_2.png',about: 'Ashley Ave, Charleston, SC 29425',latitude: 32.785696,longitude: -79.947791,content: 'Built between 1968 and 1971, the Basic Science Building, or BSB, houses not only basic science laboratories, but also the Medical University of South Carolina’s College of Graduate Studies and the College of Dental Medicine, the only dental school in South Carolina.  The construction of the building on the site of the former Porter Military Academys Porter and Summerall Halls was initially delayed when it was discovered that the site was (until 1825) a former potter’s field, a commoner’s graveyard containing more than one hundred graves.'},
    {code: 2,name: 'Colcock Hall',profilePic: 'assets/img/Colcock.png',about: '104 Colcock Hall MSC - 003, Charleston, SC 29425',latitude: 32.786655,longitude : -79.947937,content : 'In 1825, the US government acquired the land bounded by Bee, Doughty, Prescodeent, and Ashley streets. Between this time and 1832, architect E. B. White designed the Charleston Arsenal to be built on this property. The Confederate military overtook the area in 1860. During this occupation, the building now known as Colcock Hall was built for the manufacture of small arms and cannon repair. Along the current south wall, remnants of seven two-story arches can still be seen. These arches were once openings through which cannons could be brought for rebanding. In 1967, Rev. Anthony Porter created The Orphan Home and School Association of the Church of the Holy Communion as a home for boys orphaned by the US Civil War. Rev. Porter took the Charleston Arsenal area in 1880. The aforementioned arches of the cannon building were subsequently bricked up to create large classrooms. The school was renamed to Porter Military Academy in 1886. The cannon building was named Butler Hall, honoring the Confederate General Matthew Butler, a US Senator from SC who helped transfer the property to Porter Military Academy. In 1919, Butler Hall was renamed Colcock Hall after Charles J. Colcock, the second headmaster and rector of the academy. The Medical College of SC purchased the Porter Academy area in 1963 including Colcock Hall, Waring Library, and St. Lukes Chapel. Colcock was immediately renovated to house the new Dental School until the Basic Sciences Building was completed in 1970. Colcock Hall was again renovated in 2005-2006 and now is home to the Offices of Central Administration of MUSC, the Office of the Provost, and the Office of the Prescodeent.'},
    {code: 3,name: 'Colbert Education Center and Library',profilePic: 'assets/img/Colbert.png',about: '171 Ashley Ave, Charleston, SC 29425.',latitude: 32.785137,longitude : -79.947937,content : 'In 1964, the Medical University of South Carolina purchased the land alongscodee Ashley Avenue that was formerly home to Porter Military Academy. On June sixth of 1968, construction began on the building that would house the Medical University’s administrative offices, library, and student activities center. Funding for the building came as an $8.5 million grant from the Federal Department of Health, Education, and Welfare with matching funds from the state of South Carolina. The three-story structure was designed by the architecture company Lyles, Bissett, Carlisle, & Wolfe of Columbia, and is made of cast stone with a coated concrete exterior. The building was dedicated on October 23rd of 1971; however, initial construction was not complete until the next year. Between 1975 and 1976, a fourth floor was added which cost $2 million and increased the size by 25,000 square feet. In 2009, the building was rededicated and titled the Colbert Education Center and Library after James W. Colbert, Jr., MD (1920-1974), MUSCs first provost and VP of Academic Affairs.'},
    {code: 4,name: 'Wickliffe House',profilePic: 'assets/img/Wickliffe_1.png',about: '178 Ashley Ave, Charleston, SC 29403',latitude: 32.786097,longitude: -79.946657,content: 'Located at 178 Ashley Avenue, and built by John Hume Lucas, a wealthy planter, from 1850 to 1852. This house was acquired by the Health Science Foundation of the Medical University of South Carolina with funds donated by Miss Margaret Wickliffe of West Union, SC in 1977 and was used as the Faculty-Alumni House for the University. The prescodeent of the university, Dr. William Hagerman Knisely, Ph.D. was in search for funding in order to purchase the Wickliffe House. He pacode a little visit to Ms. Wickliffe in order to enquire about the donation and brought Dr. Sabin along with him. This physician was a well-known and well respected man in the field of medicine but he was not invited along to this meeting for those reasons. He was the spitting image of Ms. Wickliffes father. She was so struck by the similarity between Dr. Sabin and her father that she immediately donated the funds to the University. The Wickliffe House now is used as a restaurant and wedding venue.'},
    {code: 5,name: 'St. Lukes Chapel',profilePic: 'assets/img/StLuke2BW.png',about: '181 Ashley Ave, Charleston, SC 29425',latitude: 32.787121,longitude: -79.947482,content: 'St. Lukes Chapel sits on the site of a potters field purchased by the City of Charleston in 1807.  In 1825, the United States government acquired the property to built a federal arsenal.  Built between 1825 and 1830, the arsenal housed small arms, field artillery, and a stable.  The property was one of the first Federal properties acquired by the Confederacy during the Civil War.  After the war, it served as a military arsenal until 1879.  In 1867, the Rev. Anthony Toomer Porter founded the Holy Communion Church Institute for boys orphaned or left destitute by the Civil War.  In 1879, he acquired the arsenal and hired Holton Bell, a brick mason of African-American descent, to design and construct changes to the building to convert it into a chapel.  The roof was removed, the walls raised, a gothic roof and stained glass windows installed, and a surrounding brick wall built.  In 1886, the Holy Communication Church Institute was renamed Porter Academy, and by 1893, the school became known as the Porter Military Academy.  The chapel, known as St. Timothy’s Chapel was used every morning by the cadets, who represented all faiths.  In 1963, the Medical College of South Carolina purchased the Porter campus and the Porter Military Academy merged with the Gaud and Watts schools to become Porter-Gaud School, located west of the Ashley River.  The Medical College kept the chapel and renamed it for St. Luke, the patron saint of physicians.  On September 21, 1989, St. Luke’s Chapel was severely damaged by Hurricane Hugo.  The roof collapsed, the organ was ruined beyond repair, and the stained glass windows crashed into Bee Street.  Over $1,000,000 and four years later, the restored chapel was rededicated on February 10, 1994, a perfect combination between historical ambience and modern functionality.  A new organ was built and named in honor of Margaret Metcalf, the wife of Dr. John Fesperman, a major contributor to the construction.  The chapel is currently used for weddings, musical events, an annual memorial service to honor those who donated their bodies to science, and an annual memorial service for the Porter Military Academy Alumni Association.'},
    {code: 6,name: 'Childrens Research Institute',profilePic: 'assets/img/CRI.png',about: 'Bee st Charleston, SC 29425',latitude: 32.784453,longitude: -79.947482,content: 'The Charles Darby Children’s Research Institute was dedicated on February 18, 2005 as the premier pediatric research facility in South Carolina. One of only 15 pediatric research centers in the entire nation; this seven-story building houses 150 state-of-the-art laboratory modules focused on childhood disorders including cancer, AcodeS, diabetes, lung diseases, neurological conditions and genetics. The Children’s Research Institute’s namesake, Dr. Charles Darby, Jr. founded the internationally recognized MUSC Children’s Hospital in 1987. Dr. Darby is a Charleston native, graduate of the Citadel and MUSC College of Medicine with many years as a respected pediatrician, hospital department chair, professor, and philanthropist. His passion for all children to receive the same excellent standard of care contributed to his successful leadership and over $100 million fundraising benefiting the MUSC Children’s Hospital. Dr. Darby’s accomplishments led to a well-deserved Larry Zucker Lifetime Achievement Award in 2011. The Children’s Research Institute intersects the Basic Science Building, which was originally funded by an $8.5M United States Department of Health Education and Welfare grant provcodeing 256,533 sq. ft. of classroom space, still in use today by several of the MUSC Colleges. The 1968 construction of Basic Science was interrupted when a circa 1800 City of Charleston potter’s field with 100 unmarked graves was discovered. In 1991, a 150,000 sq. ft. expansion was added.  In 2002, the ELK Foundation of California donated $250K to renovate a 300-seat auditorium for sick children. Both buildings sit on the former grounds of Porter Military Academy.'} 
  ];
	}
 
  loadAll(){
      return Promise.resolve(this.data);
  };
  getByID(id){
    for(var i=0; i< (this.data).length; i++)
    {
      if(this.data[i].code == id)
      {
        return Promise.resolve(this.data[i]);
      }
    }
  };
}